language: emacs
sudo: false

env:
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26-pretest-travis

matrix:
  fast_finish: true

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - make ci-dependencies

script:
  - make check
