sudo: false

env:
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis

matrix:
  fast_finish: true

before_install:
  # Workaround for https://github.com/rejeep/evm/issues/109
  - source evm-install.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - make ci-dependencies

script:
  - make check
